# Generated by Django 5.0.2 on 2024-02-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notify_me',
            field=models.BooleanField(default=False),
        ),
    ]
